### ISSUE TITLE
This application failed to start because it could not find or load the Qt platform plugin "windows" in "".

### ISSUE THREAD

**Issue by hyeonki-min** [handrake/subtitle-convert#5]
error log is below:
`This application failed to start because it could not find or load the Qt platform plugin "windows"
in "".`
`Reinstalling the application may fix this problem.`

my env is below:

> python3.5.2 | Anaconda 4.2.0(64bit)
window 10

when i exec command "python -m subtitle_convert", occur error

**Comment by handrake** [comment]
@ho9science Thank you for the first report! I'll take a look at the issue this weekend.

**Comment by handrake** [comment]
@ho9science Have you tried installing Qt itself from the official website? https://www.qt.io/download

**Comment by hyeonki-min** [comment]
I try in other env.

> python3.5.4 | Anaconda 4.4.0
window 10


check out sys.path right
and it works

thank you
